AWSTemplateFormatVersion: 2010-09-09
Description: S3 for GitLabRepositoryInspector

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  VersioningStatus:
    Type: String
    AllowedValues: [Enabled, Suspended]
  isBucketKeyEnabled:
    Type: String
    AllowedValues: [true, false]
  SSEAlgorithm:
    Type: String
    AllowedValues: [aws:kms, AES256, aws:kms:dsse]
  isEventBridgeEnabled:
    Type: String
    AllowedValues: [true, false]
  AccelerationStatus:
    Type: String
    AllowedValues: [Enabled, Suspended]
  isObjectLockEnabled:
    Type: String
    AllowedValues: [true, false]
  isStaticWebsiteEnabled:
    Type: String
    AllowedValues: [true, false]
  isBlockPublicAclsEnabled:
    Type: String
    AllowedValues: [true, false]
  isIgnorePublicAclsEnabled:
    Type: String
    AllowedValues: [true, false]
  isBlockPublicPolicyEnabled:
    Type: String
    AllowedValues: [true, false]
  isRestrictPublicBucketsEnabled:
    Type: String
    AllowedValues: [true, false]
  ObjectOwnership:
    Type: String
    AllowedValues: [ObjectWriter, BucketOwnerPreferred, BucketOwnerEnforced]

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Conditions:
  isNotAES256: !Not [ !Equals [ !Ref SSEAlgorithm, AES256 ] ]
  isObjectLockEnabled: !Equals [ !Ref isObjectLockEnabled, true ]
  isStaticWebsiteEnabled: !Equals [ !Ref isStaticWebsiteEnabled, true ]

Resources:
  S3BucketArtifacts:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${SystemName}-${EnvType}-s3-artifacts-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: !Ref VersioningStatus
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !Ref SSEAlgorithm
              KMSMasterKeyID: !If
                - isNotAES256
                - !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/${SystemName}-${EnvType}-kms-s3
                - !Ref AWS::NoValue
            BucketKeyEnabled: !Ref isBucketKeyEnabled
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: !Ref isEventBridgeEnabled
      AccelerateConfiguration:
        AccelerationStatus: !Ref AccelerationStatus
      ObjectLockEnabled: !Ref isObjectLockEnabled
      ObjectLockConfiguration: !If
        - isObjectLockEnabled
        - ObjectLockEnabled: !Ref isObjectLockEnabled
          Rule:
            DefaultRetention:
              Mode: String
              Years: Integer
              Days: Integer
        - !Ref AWS::NoValue
      WebsiteConfiguration: !If
        - isStaticWebsiteEnabled
        - IndexDocument: String
          ErrorDocument: String
          RoutingRules:
            - RoutingRule
        - !Ref AWS::NoValue
      PublicAccessBlockConfiguration:
        BlockPublicAcls: !Ref isBlockPublicAclsEnabled
        IgnorePublicAcls: !Ref isIgnorePublicAclsEnabled
        BlockPublicPolicy: !Ref isBlockPublicPolicyEnabled
        RestrictPublicBuckets: !Ref isRestrictPublicBucketsEnabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: !Ref ObjectOwnership
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-s3-artifacts-${AWS::AccountId}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
