AWSTemplateFormatVersion: 2010-09-09
Description: CodePipeline for GitLabRepositoryInspector

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  ReleaseImageTag:
    Type: String

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  CodePipelineGitLabRepositoryInspector:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${SystemName}-${EnvType}-codepipeline-gitlab-repository-inspector
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${SystemName}-${EnvType}-role-codepipeline
      ArtifactStore:
        Type: S3
        Location: !Sub ${SystemName}-${EnvType}-s3-artifacts-${AWS::AccountId}-${AWS::Region}
      RestartExecutionOnUpdate: false
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: ECR
                Version: 1
              Region: !Ref AWS::Region
              Configuration:
                RepositoryName: gitlabchangelogs
                ImageTag: !Ref ReleaseImageTag
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Deploy
          Actions:
            - Name: Deploy
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Region: !Ref AWS::Region
              Configuration:
                ProjectName: !Sub ${SystemName}-${EnvType}-codebuild-gitlab-repository-inspector
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuiltArtifact
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-codepipeline-gitlab-repository-inspector
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
