AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB for GitLabRepositoryInspector

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  TableClass:
    Type: String
    AllowedValues: [STANDARD, STANDARD_INFREQUENT_ACCESS]
  BillingMode:
    Type: String
    AllowedValues: [PROVISIONED, PAY_PER_REQUEST]
  isDeletionProtectionEnabled:
    Type: String
    AllowedValues: [true, false]
  isPointInTimeRecoveryEnabled:
    Type: String
    AllowedValues: [true, false]
  isContributorInsightsSpecification:
    Type: String
    AllowedValues: [true, false]
  isTimeToLiveSpecification:
    Type: String
    AllowedValues: [true, false]

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  DynamoDbTableGitLabChangeLogs:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${SystemName}-${EnvType}-dynamodb-gitlab-change-logs
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableClass: !Ref TableClass
      BillingMode: !Ref BillingMode
      DeletionProtectionEnabled: !Ref isDeletionProtectionEnabled
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref isPointInTimeRecoveryEnabled
      ContributorInsightsSpecification:
        Enabled: !Ref isContributorInsightsSpecification
      TimeToLiveSpecification:
        Enabled: !Ref isTimeToLiveSpecification
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-dynamodb-gitlab-change-logs
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
