AWSTemplateFormatVersion: 2010-09-09
Description: Lambda for GitLabRepositoryInspector

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  gitlabchangelogsImageTag:
    Type: String
  LambdaMemorySize:
    Type: Number
  GitLabGroupName:
    Type: String
  GitLabProjectName:
    Type: String

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  LambdaGitLabRepositoryInspector:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${SystemName}-${EnvType}-lambda-gitlab-repository-inspector
      Description: !Sub ${SystemName}-${EnvType}-lambda-gitlab-repository-inspector
      PackageType: Image
      Code:
        ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/gitlabchangelogs:${gitlabchangelogsImageTag}
      Architectures:
        - x86_64
      MemorySize: !Ref LambdaMemorySize
      Timeout: 900
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/${SystemName}-${EnvType}-role-lambda-gitlab-repository-inspector
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Sub ${SystemName}-${EnvType}-dynamodb-gitlab-change-logs
          GITLAB_REPOSITORY_ACCESSTOKEN_NAME: !Sub ${SystemName}-${EnvType}-parameterstore-gitlab-repository-accesstoken
          GITLAB_REPOSITORY_URL: !Sub
            - https://gitlab.com/api/v4/projects/${GitLabGroupName}%2F${GitLabProjectName}/repository/commits
            - GitLabGroupName: !Ref GitLabGroupName
              GitLabProjectName: !Ref GitLabProjectName
          SNS_TOPIC_ARN:
            Fn::ImportValue: !Sub ${SystemName}-${EnvType}-sns-topic-arn
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-lambda-gitlab-repository-inspector
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
